apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l6dgobfnx-python 
  janus-idp.io/tekton: l6dgobfnx-python
  backstage.io/kubernetes-id: l6dgobfnx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l6dgobfnx-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  